// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2TzWkLhx6xIrG7O9H0ltCkkw6h3pCoJE',
    appId: '1:11875649217:web:2566d44b228340ccaff640',
    messagingSenderId: '11875649217',
    projectId: 'el-platform',
    authDomain: 'el-platform.firebaseapp.com',
    storageBucket: 'el-platform.appspot.com',
    measurementId: 'G-K5B5NTEX6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv4q1mYsSwtgVckeTn1veF7lkqkq-6UhY',
    appId: '1:11875649217:android:a20bfdccca44cc2aaff640',
    messagingSenderId: '11875649217',
    projectId: 'el-platform',
    storageBucket: 'el-platform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIkqZE5WmEjxwsn8ccDaG5GEWwZRR_TJU',
    appId: '1:11875649217:ios:874929c4df6103ffaff640',
    messagingSenderId: '11875649217',
    projectId: 'el-platform',
    storageBucket: 'el-platform.appspot.com',
    iosBundleId: 'com.example.gucSwissKnife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIkqZE5WmEjxwsn8ccDaG5GEWwZRR_TJU',
    appId: '1:11875649217:ios:2649232e8a3d91c9aff640',
    messagingSenderId: '11875649217',
    projectId: 'el-platform',
    storageBucket: 'el-platform.appspot.com',
    iosBundleId: 'com.example.gucSwissKnife.RunnerTests',
  );
}
